app = "antonello"
primary_region = "ams"

[processes]
  app = "daemon"

[env]
  HOME                       = "/zeroclaw-data"
  ZEROCLAW_WORKSPACE         = "/zeroclaw-data/workspace"
  PROVIDER                   = "gemini"
  ZEROCLAW_GATEWAY_PORT      = "42617"
  ZEROCLAW_GATEWAY_HOST      = "0.0.0.0"
  ZEROCLAW_ALLOW_PUBLIC_BIND = "true"

[[mounts]]
  source      = "zeroclaw_data"
  destination = "/zeroclaw-data"


[[vm]]
  size   = "shared-cpu-1x"
  memory = "256mb"
